### ISSUE TITLE
"undefined reference" errors with Qt 5.12 and mingw73_64 (mingw53_32 is gone)

### ISSUE THREAD

**Issue by pbek** [appveyor/ci#2871]
First thank you for this wonderful CI service, I love it a lot and am using it to build https://github.com/pbek/QOwnNotes.

Since a few days `C:\Qt\latest` has `mingw73_64` instead of `mingw53_32`. After changing the directory in https://github.com/pbek/QOwnNotes/blob/develop/appveyor.yml I got a huge amount of  "undefined reference" errors: <https://ci.appveyor.com/project/pbek/qownnotes/builds/22417462/job/eddeajis4cfp393n>

QOwnNotes isn't able to build with the latest Qt 5.12 version any more (as a workaround I fell back to Qt 5.11).

example:

```
release/moc_welcomedialog.o:moc_welcomedialog.cpp:(.rdata$_ZTV13WelcomeDialog[__ZTV13WelcomeDialog]+0xb8): undefined reference to `QWidget::changeEvent(QEvent*)'
```

Did I do something wrong?

**Comment by pbek** [comment]
Is there no `mingw53_32` for the latest version of Qt any more? I can only see `mingw73_64` and `msvc2015_64`.

**Comment by pbek** [comment]
@FeodorFitsner, do you by chance know where `mingw53_32` has gone in `C:\Qt\latest`? I'm asking because you were able to help us in #2502 so marvelously.

**Comment by IlyaFinkelshteyn** [comment]
@pbek sorry for delay with reply. This is a result of upgrading to Qt 5.12.1 https://github.com/appveyor/ci/issues/2760

Please check for `mingw53_32` [here](https://www.appveyor.com/docs/windows-images-software/#qt). As you can see it exists under `C:\Qt\5.11.3`, `C:\Qt\5.10.1`, `C:\Qt\5.9.7` and `C:\Qt\5.7.0`.

**Comment by pbek** [comment]
Thank you very much for your help, @IlyaFinkelshteyn!

So I need to wait for Qt 5.12.2 (https://github.com/appveyor/ci/issues/2889) to get back MinGW 32, right? Or were you referring to that I could use `mingw53_32` from Qt 5.11 with Qt 5.12? (Personally I also would use the 64 bit version, but I don't know why I get the `undefined reference` errors.)

**Comment by IlyaFinkelshteyn** [comment]
Please try now -- new images has been deployed, should help.

**Comment by pbek** [comment]
thank you very much, @IlyaFinkelshteyn, I'll test it!

**Comment by pbek** [comment]
Works perfectly, thanks a lot again!

**Comment by IlyaFinkelshteyn** [comment]
Great, sorry it took that long :)

**Comment by pbek** [comment]
Nah, thank you very much for offering your great service freely to open source software!
